version: '3'

services:
  captain-gradd:
    build: .
    command: 'bash -c ./dev-run.sh'
    ports:
      - '8887:8080'
    environment:
      NODE_ENV: development     
      ETH_NODE_URL: http://dav-contracts:8545
      DAV_API_URL: http://mission-control:8443
      CAPTAIN_PORT: 8080
      CAPTAIN_HOSTNAME: 0.0.0.0
    volumes:
      - ./build:/build
      - .:/app
    external_links:
      - missioncontrol_missioncontrol_1:mission-control
      - dav-contracts:dav-contracts
networks:
  dav:
    external: true