branch-defaults:
  master:
    environment: captain-gradd-stg1
    group_suffix: null
  production:
    environment: captain-gradd-prod
environment-defaults:
  captain-gradd-stg:
    branch: null
    repository: null
global:
  application_name: captain-gradd
  branch: null
  default_ec2_keyname: captain-gradd-key
  default_platform: Docker 17.09.1-ce
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
